In [3]:
import pandas as pd

In [12]:
log_raw = pd.read_csv('/home/zseefvhu12/projects/spark_training/data/samples/raw/01-log-tracking-sample.csv')
purchase_raw = pd.read_csv('/home/zseefvhu12/projects/spark_training/data/samples/raw/02-purchase-behavior-sample.csv')
log_bronze = pd.read_csv('/home/zseefvhu12/projects/spark_training/data/samples/bronze/log_tracking_sample.csv')
purchase_bronze = pd.read_csv('/home/zseefvhu12/projects/spark_training/data/samples/bronze/purchase_behavior_sample.csv')

In [13]:
log_raw.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 08:00:00 UTC,view,1000000,2053013555631882655,electronics.smartphone,samsung,19.99,520000000,sample-session-000
1,2019-11-01 08:17:00 UTC,cart,1000001,2053013554415534427,computers.notebook,apple,27.49,520000001,sample-session-001
2,2019-11-01 08:34:00 UTC,purchase,1000002,2053013554658804075,appliances.kitchen,xiaomi,34.99,520000002,sample-session-002
3,2019-11-01 08:51:00 UTC,view,1000003,2053013557192163841,furniture.bedroom.bed,sony,42.49,520000003,sample-session-003
4,2019-11-01 09:08:00 UTC,cart,1000004,2053013555631882655,electronics.smartphone,lg,49.99,520000004,sample-session-004

In [14]:
purchase_raw.head()

,user_id,event_time,event_type,product_id,category_id,category_code,brand,price,user_session,event_date,first_event_date,start_of_week,week_number,end_of_week,week_text,cohort_index_week,week_after
0,520000000,2019-11-01 08:00:00,purchase,1000000,2053013555631882655,electronics.smartphone,samsung,19.99,sample-session-000,2019-11-01,2019-11-01,2019-10-28,44,2019-11-03,W44,W44 (2019-10-28 -> 2019-11-03),0
1,520000001,2019-11-01 08:17:00,cart,1000001,2053013554415534427,computers.notebook,apple,27.49,sample-session-001,2019-11-01,2019-10-31,2019-10-28,44,2019-11-03,W44,W44 (2019-10-28 -> 2019-11-03),0
2,520000002,2019-11-01 08:34:00,purchase,1000002,2053013554658804075,appliances.kitchen,xiaomi,34.99,sample-session-002,2019-11-01,2019-10-30,2019-10-28,44,2019-11-03,W44,W44 (2019-10-28 -> 2019-11-03),0
3,520000003,2019-11-01 08:51:00,purchase,1000003,2053013557192163841,furniture.bedroom.bed,sony,42.49,sample-session-003,2019-11-01,2019-10-29,2019-10-28,44,2019-11-03,W44,W44 (2019-10-28 -> 2019-11-03),0
4,520000004,2019-11-01 09:08:00,cart,1000004,2053013555631882655,electronics.smartphone,lg,49.99,sample-session-004,2019-11-01,2019-10-28,2019-10-28,44,2019-11-03,W44,W44 (2019-10-28 -> 2019-11-03),0

In [15]:
log_bronze.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,event_timestamp,event_date,source_file,ingest_time,batch_id
0,2019-11-01 08:00:00 UTC,view,1000000,2053013555631882655,electronics.smartphone,samsung,19.99,520000000,sample-session-000,2019-11-01 08:00:00,2019-11-01,data/raw/01-log-tracking.csv,2026-06-16T03:02:19+00:00,sample_001
1,2019-11-01 08:17:00 UTC,cart,1000001,2053013554415534427,computers.notebook,apple,27.49,520000001,sample-session-001,2019-11-01 08:17:00,2019-11-01,data/raw/01-log-tracking.csv,2026-06-16T03:02:19+00:00,sample_001
2,2019-11-01 08:34:00 UTC,purchase,1000002,2053013554658804075,appliances.kitchen,xiaomi,34.99,520000002,sample-session-002,2019-11-01 08:34:00,2019-11-01,data/raw/01-log-tracking.csv,2026-06-16T03:02:19+00:00,sample_001
3,2019-11-01 08:51:00 UTC,view,1000003,2053013557192163841,furniture.bedroom.bed,sony,42.49,520000003,sample-session-003,2019-11-01 08:51:00,2019-11-01,data/raw/01-log-tracking.csv,2026-06-16T03:02:19+00:00,sample_001
4,2019-11-01 09:08:00 UTC,cart,1000004,2053013555631882655,electronics.smartphone,lg,49.99,520000004,sample-session-004,2019-11-01 09:08:00,2019-11-01,data/raw/01-log-tracking.csv,2026-06-16T03:02:19+00:00,sample_001

In [16]:
purchase_bronze.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,event_timestamp,...,first_event_date,start_of_week,week_number,end_of_week,week_text,cohort_index_week,week_after,source_file,ingest_time,batch_id
0,2019-11-01 08:00:00,purchase,1000000,2053013555631882655,electronics.smartphone,samsung,19.99,520000000,sample-session-000,2019-11-01 08:00:00,...,2019-11-01,2019-10-28,44,2019-11-03,W44,W44 (2019-10-28 -> 2019-11-03),0,data/raw/02-purchase-behavior.csv,2026-06-16T03:02:19+00:00,sample_001
1,2019-11-01 08:17:00,cart,1000001,2053013554415534427,computers.notebook,apple,27.49,520000001,sample-session-001,2019-11-01 08:17:00,...,2019-10-31,2019-10-28,44,2019-11-03,W44,W44 (2019-10-28 -> 2019-11-03),0,data/raw/02-purchase-behavior.csv,2026-06-16T03:02:19+00:00,sample_001
2,2019-11-01 08:34:00,purchase,1000002,2053013554658804075,appliances.kitchen,xiaomi,34.99,520000002,sample-session-002,2019-11-01 08:34:00,...,2019-10-30,2019-10-28,44,2019-11-03,W44,W44 (2019-10-28 -> 2019-11-03),0,data/raw/02-purchase-behavior.csv,2026-06-16T03:02:19+00:00,sample_001
3,2019-11-01 08:51:00,purchase,1000003,2053013557192163841,furniture.bedroom.bed,sony,42.49,520000003,sample-session-003,2019-11-01 08:51:00,...,2019-10-29,2019-10-28,44,2019-11-03,W44,W44 (2019-10-28 -> 2019-11-03),0,data/raw/02-purchase-behavior.csv,2026-06-16T03:02:19+00:00,sample_001
4,2019-11-01 09:08:00,cart,1000004,2053013555631882655,electronics.smartphone,lg,49.99,520000004,sample-session-004,2019-11-01 09:08:00,...,2019-10-28,2019-10-28,44,2019-11-03,W44,W44 (2019-10-28 -> 2019-11-03),0,data/raw/02-purchase-behavior.csv,2026-06-16T03:02:19+00:00,sample_001

In [23]:
log_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_time     100 non-null    str
 1   event_type     100 non-null    str
 2   product_id     100 non-null    int64
 3   category_id    100 non-null    int64
 4   category_code  100 non-null    str
 5   brand          100 non-null    str
 6   price          100 non-null    float64
 7   user_id        100 non-null    int64
 8   user_session   100 non-null    str
dtypes: float64(1), int64(3), str(5)
memory usage: 7.2 KB

In [24]:
purchase_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            100 non-null    int64
 1   event_time         100 non-null    str
 2   event_type         100 non-null    str
 3   product_id         100 non-null    int64
 4   category_id        100 non-null    int64
 5   category_code      100 non-null    str
 6   brand              100 non-null    str
 7   price              100 non-null    float64
 8   user_session       100 non-null    str
 9   event_date         100 non-null    str
 10  first_event_date   100 non-null    str
 11  start_of_week      100 non-null    str
 12  week_number        100 non-null    int64
 13  end_of_week        100 non-null    str
 14  week_text          100 non-null    str
 15  cohort_index_week  100 non-null    str
 16  week_after         100 non-null    int64
dtypes: float64(1), int64(5), str(11)
memory usage: 13.4 KB

In [21]:
log_bronze.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_time       100 non-null    str
 1   event_type       100 non-null    str
 2   product_id       100 non-null    int64
 3   category_id      100 non-null    int64
 4   category_code    100 non-null    str
 5   brand            100 non-null    str
 6   price            100 non-null    float64
 7   user_id          100 non-null    int64
 8   user_session     100 non-null    str
 9   event_timestamp  100 non-null    str
 10  event_date       100 non-null    str
 11  source_file      100 non-null    str
 12  ingest_time      100 non-null    str
 13  batch_id         100 non-null    str
dtypes: float64(1), int64(3), str(10)
memory usage: 11.1 KB

In [22]:
purchase_bronze.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   event_time         100 non-null    str
 1   event_type         100 non-null    str
 2   product_id         100 non-null    int64
 3   category_id        100 non-null    int64
 4   category_code      100 non-null    str
 5   brand              100 non-null    str
 6   price              100 non-null    float64
 7   user_id            100 non-null    int64
 8   user_session       100 non-null    str
 9   event_timestamp    100 non-null    str
 10  event_date         100 non-null    str
 11  first_event_date   100 non-null    str
 12  start_of_week      100 non-null    str
 13  week_number        100 non-null    int64
 14  end_of_week        100 non-null    str
 15  week_text          100 non-null    str
 16  cohort_index_week  100 non-null    str
 17  week_after         100 non-null    int64
 18  source_file        100 non-null    str
 19  ingest_time        100 non-null    str
 20  batch_id           100 non-null    str
dtypes: float64(1), int64(5), str(15)
memory usage: 16.5 KB

In [27]:
data_quality = pd.read_csv('/home/zseefvhu12/projects/spark_training/results/data_profiles.csv')
data_quality.head(40)

,run_id,layer,dataset,column_name,data_type,row_count,null_count,null_rate,empty_count,empty_rate,approx_distinct_count,mode_value,mode_count,min_value,max_value,avg_value,stddev_value,profiled_at
0,20260616_040855,raw,log_tracking,event_time,string,67501979,0,0.000000,0,0.0,2723117,2019-11-15 02:51:51 UTC,243,2019-11-01 00:00:00 UTC,2019-11-30 23:59:59 UTC,NaN,NaN,2026-06-16T04:09:03+00:00
1,20260616_040855,raw,log_tracking,event_type,string,67501979,0,0.000000,0,0.0,3,view,63556110,cart,view,NaN,NaN,2026-06-16T04:09:03+00:00
2,20260616_040855,raw,log_tracking,product_id,string,67501979,0,0.000000,0,0.0,188102,1005115,670649,100000000,9900463,NaN,NaN,2026-06-16T04:09:03+00:00
3,20260616_040855,raw,log_tracking,category_id,string,67501979,0,0.000000,0,0.0,671,2053013555631882655,16375000,2053013552226107603,2187707861038006932,NaN,NaN,2026-06-16T04:09:03+00:00
4,20260616_040855,raw,log_tracking,category_code,string,67501979,21898171,0.324408,0,0.0,128,electronics.smartphone,16375000,accessories.bag,stationery.cartrige,NaN,NaN,2026-06-16T04:09:03+00:00
5,20260616_040855,raw,log_tracking,brand,string,67501979,9218235,0.136562,0,0.0,4328,samsung,7889245,a-case,zyxel,NaN,NaN,2026-06-16T04:09:03+00:00
6,20260616_040855,raw,log_tracking,price,string,67501979,0,0.000000,0,0.0,57905,154.42,266181,0.00,999.82,NaN,NaN,2026-06-16T04:09:03+00:00
7,20260616_040855,raw,log_tracking,user_id,string,67501979,0,0.000000,0,0.0,3665069,568778435,22929,100963605,97129396,NaN,NaN,2026-06-16T04:09:03+00:00
8,20260616_040855,raw,log_tracking,user_session,string,67501979,10,0.000000,0,0.0,13756115,d99d91bf-40f8-4e29-9593-54b4a1826542,4128,0000007c-adbf-4ed7-af17-d1fef9763d67,fffffde2-4522-4b44-8a32-510c55739ba1,NaN,NaN,2026-06-16T04:09:03+00:00
9,20260616_040855,raw,purchase_behavior,user_id,string,916939,0,0.000000,0,0.0,459516,564068124,519,138340325,579967058,NaN,NaN,2026-06-16T04:11:20+00:00
10,20260616_040855,raw,purchase_behavior,event_time,string,916939,0,0.000000,0,0.0,630794,2019-11-18 00:59:26,21,2019-11-01 07:00:41,2019-12-01 06:59:44,NaN,NaN,2026-06-16T04:11:20+00:00
11,20260616_040855,raw,purchase_behavior,event_type,string,916939,0,0.000000,0,0.0,1,purchase,916939,purchase,purchase,NaN,NaN,2026-06-16T04:11:20+00:00
12,20260616_040855,raw,purchase_behavior,product_id,string,916939,0,0.000000,0,0.0,56052,1004856,32321,100000003,9900463,NaN,NaN,2026-06-16T04:11:20+00:00
13,20260616_040855,raw,purchase_behavior,category_id,string,916939,0,0.000000,0,0.0,622,2053013555631882655,382647,2053013552226107603,2187707789055361298,NaN,NaN,2026-06-16T04:11:20+00:00
14,20260616_040855,raw,purchase_behavior,category_code,string,916939,234218,0.255435,0,0.0,124,electronics.smartphone,382647,accessories.bag,stationery.cartrige,NaN,NaN,2026-06-16T04:11:20+00:00
15,20260616_040855,raw,purchase_behavior,brand,string,916939,73273,0.079910,0,0.0,2493,samsung,200027,a-case,zvezda,NaN,NaN,2026-06-16T04:11:20+00:00
16,20260616_040855,raw,purchase_behavior,price,string,916939,0,0.000000,0,0.0,23790,128.42,7891,0.77,999.65,NaN,NaN,2026-06-16T04:11:20+00:00
17,20260616_040855,raw,purchase_behavior,user_session,string,916939,0,0.000000,0,0.0,758230,68b52b9a-97c8-4525-aba2-604ede028da8,100,0000145a-b981-424b-ba76-5e8f50beb12d,fffffd01-5f95-4916-b2dd-491c603d6c9c,NaN,NaN,2026-06-16T04:11:20+00:00
18,20260616_040855,raw,purchase_behavior,event_date,string,916939,0,0.000000,0,0.0,31,2019-11-17,166319,2019-11-01,2019-12-01,NaN,NaN,2026-06-16T04:11:20+00:00
19,20260616_040855,raw,purchase_behavior,first_event_date,string,916939,0,0.000000,0,0.0,31,2019-11-17,151703,2019-11-01,2019-12-01,NaN,NaN,2026-06-16T04:11:20+00:00
20,20260616_040855,raw,purchase_behavior,start_of_week,string,916939,0,0.000000,0,0.0,5,2019-11-11,323667,2019-10-28,2019-11-25,NaN,NaN,2026-06-16T04:11:20+00:00
21,20260616_040855,raw,purchase_behavior,week_number,string,916939,0,0.000000,0,0.0,5,46,323667,44,48,NaN,NaN,2026-06-16T04:11:20+00:00
22,20260616_040855,raw,purchase_behavior,end_of_week,string,916939,0,0.000000,0,0.0,5,2019-11-05,323667,2019-10-22,2019-11-19,NaN,NaN,2026-06-16T04:11:20+00:00
23,20260616_040855,raw,purchase_behavior,week_text,string,916939,0,0.000000,0,0.0,5,W46,323667,W44,W48,NaN,NaN,2026-06-16T04:11:20+00:00
24,20260616_040855,raw,purchase_behavior,cohort_index_week,string,916939,0,0.000000,0,0.0,5,W46 (2019-11-11 ➜ 2019-11-05),323667,W44 (2019-10-28 ➜ 2019-10-22),W48 (2019-11-25 ➜ 2019-11-19),NaN,NaN,2026-06-16T04:11:20+00:00
25,20260616_040855,raw,purchase_behavior,week_after,string,916939,0,0.000000,0,0.0,5,0,745317,0,4,NaN,NaN,2026-06-16T04:11:20+00:00